### PR TITLE
adding SubToMe for the RSS link. It should be easier to subscribe to RSS...

### PR DESCRIPTION
**Pull request by julien51**
... feeds without a copy/paste

### CODE REVIEW

**Comment by frabcus** [comment]
I've tried out the patch but I don't really feel like it helps. In particular, the first time you use it you get this message:

"You have not selected your prefered services yet. Please, pick one!"

My suspicion is that most people who even know what RSS is would just want the link to the file to open and find that annoying. And other people will use Youtube or iTunes or Email.

Thanks though!

**Comment by julien51** [comment]
Francis,

If you don't see any prefered service it's because you do not seem to be
using a Feed Reader that has registered you as using them.
SubToMe provides a transparent registration mechanism for readers
https://www.subtome.com/#/developers

The benefit of this is that you will immediately see the services you've
used in the past listed on that page.

Also, yes most person who know how to use RSS, will be able to use it. The
problem is that those who don't know how to use it, will just not use it
and will only use proprietary silos like iTunes or Youtube, or accept to
get emails which are not very useful when you listen to a podcast.

Try to put yourself in the shoes of someone who does not know what RSS is
(and should not/care about it either!).

Thanks,

## 

*Got a blog? Make following it simple: https://www.subtome.com/
*

Julien Genestoux,
http://twitter.com/julien51

+1 (415) 830 6574
+33 (0)9 70 44 76 29

**Comment by frabcus** [comment]
Sure, but somebody who doesn't know how to use it won't click it, and
even if they do the default experience doesn't guide them through
registering for a reader.

Web Intents, a small project at Google, tried to address this, and got
quite a few Chrome plugin installs of news readers. But I think it
died away in the end.

It's great that you're trying to get RSS to be popular! Totally agree
with you that we need to break subscription out of those silos.

I just don't think this will help. SubToMe needs to guide new users
forcefully into picking a newsreader, and offer an option to just get
the underlying link for more technical users.

Francis

On Thu, Oct 17, 2013 at 01:21:01AM -0700, Julien Genestoux wrote:

> Francis,
> 
> If you don't see any prefered service it's because you do not seem to be
> using a Feed Reader that has registered you as using them.
> SubToMe provides a transparent registration mechanism for readers
> https://www.subtome.com/#/developers
> 
> The benefit of this is that you will immediately see the services you've
> used in the past listed on that page.
> 
> Also, yes most person who know how to use RSS, will be able to use it. The
> problem is that those who don't know how to use it, will just not use it
> and will only use proprietary silos like iTunes or Youtube, or accept to
> get emails which are not very useful when you listen to a podcast.
> 
> Try to put yourself in the shoes of someone who does not know what RSS is
> (and should not/care about it either!).
> 
> Thanks,
> 
> ## 
> 
> *Got a blog? Make following it simple: https://www.subtome.com/
> *
> 
> Julien Genestoux,
> http://twitter.com/julien51
> 
> +1 (415) 830 6574
> +33 (0)9 70 44 76 29
> 
> On Thu, Oct 17, 2013 at 1:52 AM, Francis Irving notifications@github.comwrote:
> 
> > I've tried out the patch but I don't really feel like it helps. In
> > particular, the first time you use it you get this message:
> > 
> > "You have not selected your prefered services yet. Please, pick one!"
> > 
> > My suspicion is that most people who even know what RSS is would just want
> > the link to the file to open and find that annoying. And other people will
> > use Youtube or iTunes or Email.
> > 
> > Thanks though!
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/redecentralize/redecentralize-website/pull/24#issuecomment-26469265
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/redecentralize/redecentralize-website/pull/24#issuecomment-26486501

## 

Do _you_ have an awesome idea you never quite manage to do? 
http://www.awesomefoundation.org/en/chapters/liverpool/

**Comment by julien51** [comment]
Francis,
Thanks for taking the time to discuss with me. SubToMe is in its very early stage, so it's important that we gather feedback and try to make it fit everyone's needs.

SubToMe was actually created after WebIntents were deprecated. One of the apps (http://msgboy.com) I built was one of the very few apps that supported WebIntents. Check [SubToMe's readme](https://github.com/superfeedr/subtome/blob/master/README.md) about that! We were also one of the very first people [to actually write](http://blog.superfeedr.com/webintents/) about them.

Are you able to track how many people click on the RSS link? My bet is that it's already very very low, even for a tech-aware crowd: copying and pasting urls does not work, even for us. We just don't do it, because it's too much work. If you could track that (number of clicks on the Subscribe dropdown, and then on the RSS link), that would be a great "target" in terms of what we should achieve.

Now, I perfectly agree that the workflow  for first time users who have never used any reader is not great. We're working on it. (I'd love your feeback on [this design](https://github.com/superfeedr/subtome/issues/45) submitted by someone who had the same concern). One thing you could do as a publisher to mitigate that is to suggest your users what readers they could use. See "Custom Way" on [that page](https://www.subtome.com/#/publishers).

Again, thanks a lot for your help! 

PS: also, the subToMe modal actually has a link to the original feed! (orange icon).

**Pull request closed without merging**
