### PR TITLE
Local chapter

### PR DESCRIPTION
**Pull request by pierreozoux**
Hi, here is to open the discussion about having blog for local activities. Please feel free to comment or merge ;)

### CODE REVIEW

**Comment by rossjones** [comment]
I will get to these PRs, I promise, but I'm about to go on Holiday, unless @frabcus gets to it before me, I'll check and merge them when I get back next week.

**Comment by pierreozoux** [comment]
No problems, take your time, holidays are more important ;) I'm reading the book about the swarm in the mean time!

**Comment by pierreozoux** [comment]
Any news on that?

**Comment by pierreozoux** [comment]
Just say no if you don't want to merge it, then we'll create our own blog, but I thought it was nice to reuse the branding, the network and so on..

**Comment by rossjones** [comment]
Pierre, I am _so_ sorry to let this drag out so long. I _PROMISE_ I will merge this today. I've just been very distracted recently.

**Comment by rossjones** [comment]
Done.  Thank you very much for doing this, and apologies again for taking an absolute age to do it :(

**Comment by pierreozoux** [comment]
Ouh! It's getting on! Great, thank you very much!
We organise an event Wednseday, and I thinking of putting this there :) http://www.meetup.com/Internet-Freedom-Lisbon/

Cheers, have a nice day ;)

**Comment by rossjones** [comment]
That would be great.  I'm all geared up for pushing today, so if you want any new pages ...  will discuss with others about just letting you push yourself, don't think it'll be a problem.

**Pull request merged**
